### ISSUE TITLE
CIDR not supported

### ISSUE THREAD

**Issue by simoncarbajal** [chamini2/hapi-auth-ip-whitelist#7]
The `ip` library that you are using doesn't match IPv4 ranges written in CIDR notation, this results in "Internal Server Error" when using `hapi-auth-ip-whitelist`.

The `ip` source code: 
```javascript
var ipv4Regex = /^(\d{1,3}\.){3,3}\d{1,3}$/;

ip.isV4Format = function(ip) {
  return ipv4Regex.test(ip);
};
```
Clearly the regex will never match a CIDR IP range.

https://github.com/indutny/node-ip/blob/43e442366bf5a93493c8c4c36736f87d675b0c3d/lib/ip.js#L87

**Comment by chamini2** [comment]
In https://github.com/chamini2/hapi-auth-ip-whitelist#address-ranges you can see an example of CIDR notation. 

```js
server.auth.strategy(
  'mercado-pago-webhook',
  'ip-whitelist',
  ['209.225.49.0/24', '216.33.197.0/24', '216.33.196.0/24', '63.128.82.0/24', '63.128.83.0/24', '63.128.94.0/24']  
);
````

Doesn't this work for you?

**Comment by simoncarbajal** [comment]
No.

hapi-auth-ip-whitelist is making this calls (in this order)
1. ip.isEqual() https://github.com/indutny/node-ip/blob/43e442366bf5a93493c8c4c36736f87d675b0c3d/lib/ip.js#L268
2. a = ip.toBuffer(a); https://github.com/indutny/node-ip/blob/43e442366bf5a93493c8c4c36736f87d675b0c3d/lib/ip.js#L7
3. Now here since the CIDR doesn't match the regular expressions  
```javascript
var ipv4Regex = /^(\d{1,3}\.){3,3}\d{1,3}$/;
var ipv6Regex =
    /^(::)?(((\d{1,3}\.){3}(\d{1,3}){1})?([0-9a-f]){0,4}:{0,2}){1,8}(::)?$/i;
```
4. An exception is thrown https://github.com/indutny/node-ip/blob/43e442366bf5a93493c8c4c36736f87d675b0c3d/lib/ip.js#L57

I wonder how is this working for you....

**Comment by chamini2** [comment]
Have you had the chance to run the plugin? The first thing we do ([line 22](https://github.com/chamini2/hapi-auth-ip-whitelist/blob/master/lib/index.js#L22)) with any IP passed in is check if it has the correct format before calling to `isEqual`, to avoid such exceptions.

I have just updated the example server so you can do:

```
git clone git@github.com:chamini2/hapi-auth-ip-whitelist.git
cd hapi-auth-ip-whitelist
yarn
yarn start
```

and then navigate to http://localhost:3000/ to test it yourself.

Let me know if you have further doubts.

**Comment by simoncarbajal** [comment]
It seems that you haven't published the latest updates in NPM, I added the library with this command:
`yarn add hapi-auth-ip-whitelist`

Now I copy paste the command and the result (what I have in node_modules):
```
$ cat node_modules/hapi-auth-ip-whitelist/lib/index.js
const ipIsEqual = require('ip').isEqual
const unauthorized = require('boom').unauthorized
const pkg = require('../package')

exports.plugin = {
  name: pkg.name,
  version: pkg.version,
  pkg,
  register(server, options) {
    server.auth.scheme('ip-whitelist', ipWhitelistScheme)
  }
}

function ipWhitelistScheme(server, whitelisted) {
  return {
    authenticate(request, h) {
      const { remoteAddress } = request.info

      const list = whitelisted instanceof Array ? whitelisted : [whitelisted]
      if (list.some(ip => ipIsEqual(ip, remoteAddress))) {
        return h.authenticated({ credentials: remoteAddress })
      }

      throw unauthorized(`${remoteAddress} is not a valid IP`)
    }
  }
}
```

**Comment by chamini2** [comment]
Ugh, seems like it! Let me get that done.

**Comment by chamini2** [comment]
https://www.npmjs.com/package/hapi-auth-ip-whitelist published! Let me know if now it's good.
