### ISSUE TITLE
IP validation always returning "127.0.0.1"

### ISSUE THREAD

**Issue by slinkstep** [chamini2/hapi-auth-ip-whitelist#8]
I have tested the library with an API deployed in AWS but it always is saying that receives requests from "127.0.0.1" localhost. Is there a way to make it recognize the real IP for the request 

I have used this code in the past to extract real IP from requests:

` const ip = request.headers['x-forwarded-for']
        ? request.headers['x-forwarded-for'].split(',')[0]
        : request.headers['x-real-ip'] || request.info.remoteAddress`

**Comment by chamini2** [comment]
I think you would be interested in this section of the readme: https://github.com/chamini2/hapi-auth-ip-whitelist#behind-proxy

**Comment by chamini2** [comment]
Please let me know if that was not a solution for you.
